# general settings
name: Deep_FLIM_3D_BasicVSRPlusPlus
model_type: VideoRecurrentModel
scale: 1
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: FLIM_3D
    type: train3DDataset
    dataroot_gt: datasets/ben_frames/splitting_2/trainB
    dataroot_lq: datasets/ben_frames/splitting_2/trainA
    meta_info_file: options/FLIM3D/meta_info/FLIM_meta_info_ben2.txt
    io_backend:
      type: disk

    num_frame: 100
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    gray: false
    img_ext: tif

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: FLIM_3D
    type: VideoRecurrentTestDataset
    dataroot_gt: datasets/ben_frames/splitting_2/valB
    dataroot_lq: datasets/ben_frames/splitting_2/valA
    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # not needed
    gray: false
    img_ext: tif


# network structures
network_g:
  type: BasicVSRPlusPlus
  mid_channels: 32
  num_blocks: 8


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 100000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.25

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
    ssim:
      type: calculate_ssim
      crop_border: 0

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
